global using AngleSharp;
global using ErrorOr;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using WebScrapping.Configuration;
global using WebScrapping.DTO;
global using WebScrapping.Handlers.Requests;
global using WebScrapping.Handlers.Responses;
global using WebScrapping.Services;
global using static Microsoft.AspNetCore.Http.StatusCodes;